# Generated by Django 4.2.16 on 2024-09-13 09:00

from django.db import migrations

def add_default_product_types(apps, schema_editor):
    ProductType = apps.get_model('productApp', 'ProductType')
    ProductType.objects.get_or_create(name='Tarjeta crédito')
    ProductType.objects.get_or_create(name='Cheque')
    ProductType.objects.get_or_create(name='Talonario')

class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_product_types),
    ]


from django.db import migrations
